version: "3.7"

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - /home/node/app/node_modules
      - ./src:/home/node/app/src
    container_name: gateway-docker
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm run dev
